export const HOW_TO_PLAY_MODES = [
  { icon: '🎯', title: 'Solo Quiz', desc: 'Choose 5, 10, or 15 questions and play through them at your own pace. Each correct answer earns coins, with a small completion bonus and a perfect-score bonus if you get every question right.' },
  { icon: '📅', title: 'Daily Challenge', desc: 'A new shared quiz unlocks for everyone at the same time, separately for football and basketball. Everyone gets the same questions, so it comes down to score first and completion time second. You can only play it once per day, and it pays double coins compared to a solo run.' },
  { icon: '⚔️', title: 'Online 1v1', desc: 'Create or join a real-time head-to-head room against another player. You both answer the same set of questions — the first person to answer correctly wins that point. If the match ends in a tie, a tiebreaker question decides the winner.' },
  { icon: '👥', title: 'Team Battle', desc: 'Create a team room and invite other players using their Player ID. Each teammate gets their own set of questions to answer, and your individual scores combine into a total team score. Teams need a balanced roster before the match can start, and the winning team splits the coin payout.' },
  { icon: '⚡', title: 'Lightning Solo', desc: 'A fast-paced 60-second mode — answer as many questions as you can before time runs out. Your score is based on how many you get right, and your best runs appear on the Lightning leaderboard for your sport.' },
  { icon: '⚡', title: 'Lightning 1v1', desc: 'Invite a friend using their Player ID to a 60-second duel. Both players stake coins to enter, and whoever scores higher takes the entire pot. A draw refunds both players their stake.' },
  { icon: '🏆', title: 'Tournament', desc: 'Join or create a single-elimination bracket tournament — public tournaments anyone can browse and join, or private ones shared with a 6-character code. As players win matches they advance through the bracket automatically until a champion is crowned.' },
  { icon: '🥊', title: 'Best of 3', desc: 'A 3-round series against another player — first to win 2 rounds takes the match. Both players stake coins to enter, there\'s a short break between rounds, and the winner takes the full pot. Leaving mid-series counts as a forfeit.' },
  { icon: '🔗', title: 'Common Link', desc: 'You\'re given three players or clues that share a hidden connection — figure out what links them from the multiple-choice options. Correct answers earn coins just like a solo quiz.' },
  { icon: '🎉', title: 'Seasonal Events', desc: 'Limited-time quizzes that run for a set window with their own question sets. Some events have an entry fee in coins, but rewards are boosted by a coin multiplier — the better you score, the more that multiplier pays off.' },
]